format = """
$sudo\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nix_shell\
$python\
$cmd_duration\
$fill\
$jobs\
$time\
$line_break\
$character
"""
[nix_shell]
disabled = false
format = '[$state]($style) '
impure_msg = '[❄️](bold red)'
pure_msg = '[❄️](bold blue)'

[os]
disabled = false
format = "[$symbol]($style)"
style = '#5E81AC'

[hostname]
format = '[$ssh_symbol$hostname]($style) in '
ssh_symbol = ">_"
style = 'bold dimmed green'

[directory]
read_only = " 󰌾"
style = "#81A1C1"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "#EBCB8B"
symbol = ""

[git_commit]
commit_hash_length = 7
disabled = false
format = '[ $hash $tag]($style) '
only_detached = false
style = "#EBCB8B"
tag_disabled = false
tag_symbol = ""

[git_status]
ahead = '[󱦲${count}](#A3BE8C)'
behind = '[󱦳${count}](#D08770)'
conflicted = '[!](#BF616A)'
deleted = '[-](#BF616A)'
diverged = '[${ahead_count}/${behind_count}](#D08770)'
format = "$conflicted$deleted$renamed$modified$staged$untracked$typechanged$stashed "
modified = '[±](#EBCB8B)'
renamed = '[~](#B48EAD)'
staged = '[+$count](#A3BE8C)'
stashed = '[s](bold #4C566A)'
style = "#B48EAD"
typechanged = '[*](cyan)'
untracked = '[.](#D08770)'
up_to_date = '[✓](#A3BE8C)'

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[python]
format = '[${symbol}${pyenv_prefix}([${version} ](#D8DEE9))[(\($virtualenv\) )](#B48EAD)]($style)'
style = "#EBCB8B"
symbol = " "

[cmd_duration]
disabled = false
format = "[$duration]($style) "
style = "#8FBCBB"

[fill]
symbol = " "
# style = 'bg:#4C566A'

[time]
disabled = false
format = "[ $time]($style)"
style = "italic #D8DEE9"
time_format = '%a, %b %d - %T'

[line_break]
disabled = false

[jobs]
style = "#5E81AC"
symbol = '✦'

[character] # The name of the module we are configuring is 'character'
error_symbol = '[\$ ](red)'     # '[✖](red)'     # The 'error_symbol' segment is being set to '➜' with the color 'bold red'
format = "$symbol"
success_symbol = '[\$ ](green)' # '[](green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "
Redhat = " "
Redox = "󰀘 "
SUSE = " "
Solus = "󰠳 "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
openSUSE = " "
